// ---------------------------------------------------------------------------
// Repo packer — inspired by Repomix.
//
// After cloning a service repo we pack its contents into a single structured
// file at repos/<owner>/<repo>/packed.md (or .xml).
//
// Why: the packed file can be attached directly to a Claude Code session,
// Cursor, or any AI tool without requiring the user to know which files
// exist. It is also a stable reference that doesn't change on re-runs unless
// the repo changes.
//
// The packer intentionally includes MORE file types than the migration scanner
// (which only looks at source code). Docs, config files, schemas — all of it
// helps Claude understand the full picture.
// ---------------------------------------------------------------------------

import { promises as fs } from "fs";
import { join, relative } from "path";

// ---------------------------------------------------------------------------
// What to include / exclude
// ---------------------------------------------------------------------------

const INCLUDE_EXTENSIONS = new Set([
  // Source — modern
  ".cs", ".vb", ".java", ".py", ".go", ".ts", ".js", ".tsx", ".jsx",
  ".rb", ".php", ".cpp", ".c", ".h", ".hpp", ".swift", ".kt", ".rs", ".scala",
  // Legacy enterprise languages (Feature 2: Delphi, Pascal, VB6, C++)
  ".pas", ".dpr", ".dpk", ".dfm", ".dcu",   // Delphi / Pascal
  ".bas", ".frm", ".cls", ".vbp", ".ctl",   // VB6
  ".cob", ".cbl", ".cpy",                   // COBOL
  ".pli", ".pl1",                           // PL/I
  ".f", ".f90", ".f95", ".for",             // Fortran
  // Contracts
  ".wsdl", ".xsd", ".proto", ".thrift", ".avsc",
  // Config / project
  ".json", ".yaml", ".yml", ".toml", ".xml", ".config", ".env.example",
  ".csproj", ".sln", ".pom", ".gradle", ".mod", ".sum",
  // Docs
  ".md", ".txt", ".rst",
  // SQL
  ".sql",
]);

const ALWAYS_SKIP_DIRS = new Set([
  "node_modules", ".git", ".svn", ".hg",
  "bin", "obj",
  "dist", "build", "out",
  "target",
  "__pycache__", ".venv", "venv", "env",
  ".next", ".nuxt", ".output",
  ".vs", ".idea", ".vscode",
  "coverage", ".nyc_output",
  "vendor",
  "packages",
  ".gradle",
]);

const SKIP_FILES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lockb",
  "Gemfile.lock",
  "poetry.lock",
]);

// Skip files larger than this (binary, generated, minified)
const MAX_FILE_BYTES = 150_000;

// ---------------------------------------------------------------------------
// File collection
// ---------------------------------------------------------------------------

interface PackedFile {
  path: string;
  content: string;
  lines: number;
  sizeBytes: number;
}

async function collectFiles(
  dir: string,
  base: string,
  acc: PackedFile[],
): Promise<void> {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }

  // Sort for deterministic output
  entries.sort((a, b) => {
    if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
    return a.name.localeCompare(b.name);
  });

  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;

    const full = join(dir, entry.name);
    const rel = relative(base, full);

    if (entry.isDirectory()) {
      if (ALWAYS_SKIP_DIRS.has(entry.name)) continue;
      await collectFiles(full, base, acc);
    } else {
      if (SKIP_FILES.has(entry.name)) continue;
      const dot = entry.name.lastIndexOf(".");
      if (dot === -1) continue;
      const ext = entry.name.slice(dot).toLowerCase();
      if (!INCLUDE_EXTENSIONS.has(ext)) continue;

      try {
        const stat = await fs.stat(full);
        if (stat.size > MAX_FILE_BYTES) continue;
        const content = await fs.readFile(full, "utf-8");
        acc.push({
          path: rel,
          content,
          lines: content.split("\n").length,
          sizeBytes: stat.size,
        });
      } catch { /* unreadable or binary — skip */ }
    }
  }
}

// ---------------------------------------------------------------------------
// Output formatters
// ---------------------------------------------------------------------------

function buildMarkdown(files: PackedFile[], repoName: string): string {
  const header = [
    `# ${repoName} — Packed Repository`,
    ``,
    `_Generated by CCS Code migration scanner for AI-assisted rewriting._`,
    `_Attach this file to a Claude Code / Cursor / Codex session for full repo context._`,
    ``,
    `**Files:** ${files.length}  |  **Total lines:** ${files.reduce((s, f) => s + f.lines, 0).toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## Directory Structure`,
    ``,
    "```",
  ];

  for (const f of files) {
    const depth = f.path.split("/").length - 1;
    const indent = "  ".repeat(depth);
    const name = f.path.split("/").pop() ?? f.path;
    header.push(`${indent}${name}  (${f.lines} lines)`);
  }
  header.push("```", "", "---", "");

  const fileBlocks = files.map((f) => {
    const ext = f.path.split(".").pop() ?? "";
    return [
      `## File: \`${f.path}\``,
      ``,
      `\`\`\`${ext}`,
      f.content,
      `\`\`\``,
    ].join("\n");
  });

  return header.join("\n") + "\n" + fileBlocks.join("\n\n");
}

function buildXml(files: PackedFile[], repoName: string): string {
  const escape = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const fileNodes = files.map((f) => {
    const ext = f.path.split(".").pop() ?? "";
    return [
      `  <file path="${escape(f.path)}" lines="${f.lines}" lang="${ext}">`,
      `    <![CDATA[`,
      f.content,
      `    ]]>`,
      `  </file>`,
    ].join("\n");
  });

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Packed by CCS Code migration scanner. Attach to Claude/Cursor/Codex for full repo context. -->`,
    `<repository name="${escape(repoName)}" files="${files.length}">`,
    ...fileNodes,
    `</repository>`,
  ].join("\n");
}

function buildPlain(files: PackedFile[], repoName: string): string {
  const lines: string[] = [
    `Repository: ${repoName}`,
    `Files: ${files.length}`,
    `The following text is a packed repository for AI consumption.`,
    `Each file starts with ---- followed by the file path.`,
    ``,
  ];

  for (const f of files) {
    lines.push("----");
    lines.push(f.path);
    lines.push(f.content);
    lines.push("");
  }

  lines.push("--END--");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type PackFormat = "markdown" | "xml" | "plain";

export interface PackResult {
  outputPath: string;
  fileCount: number;
  totalLines: number;
  totalTokenEstimate: number;
  format: PackFormat;
  skippedLarge: number;
}

export async function packRepo(
  repoDir: string,
  format: PackFormat = "markdown",
): Promise<PackResult> {
  const repoName = repoDir.split("/").slice(-2).join("/");
  const ext = format === "xml" ? "xml" : format === "plain" ? "txt" : "md";
  const outputPath = join(repoDir, `packed.${ext}`);

  const files: PackedFile[] = [];
  await collectFiles(repoDir, repoDir, files);

  // Skip the packed file itself if it exists from a previous run
  const filtered = files.filter((f) => !f.path.startsWith("packed."));

  let content: string;
  switch (format) {
    case "xml":   content = buildXml(filtered, repoName); break;
    case "plain": content = buildPlain(filtered, repoName); break;
    default:      content = buildMarkdown(filtered, repoName); break;
  }

  await fs.writeFile(outputPath, content, "utf-8");

  const totalLines = filtered.reduce((s, f) => s + f.lines, 0);
  const totalTokenEstimate = Math.ceil(content.length / 4);

  return {
    outputPath,
    fileCount: filtered.length,
    totalLines,
    totalTokenEstimate,
    format,
    skippedLarge: 0,
  };
}

export function formatPackStats(result: PackResult): string {
  const tokens = result.totalTokenEstimate >= 1000
    ? `${(result.totalTokenEstimate / 1000).toFixed(1)}K tokens`
    : `${result.totalTokenEstimate} tokens`;
  return `Packed ${result.fileCount} files, ${result.totalLines.toLocaleString()} lines (~${tokens})`;
}
