import { promises as fs } from "node:fs";
import { join } from "node:path";
import type { ComponentAnalysis, FrameworkInfo } from "./rewriteTypes.js";
import type { ComponentVerification } from "./rewriteVerifier.js";
import type { RunLayout } from "./runLayout.js";

export type TestScaffoldSummary = {
  dir: string;
  files: Array<{
    component: string;
    path: string;
    scenarioCount: number;
    status: "ready" | "needs_review" | "blocked";
  }>;
};

function slugify(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase() || "component";
}

function statusFor(analysis: ComponentAnalysis, verification?: ComponentVerification): "ready" | "needs_review" | "blocked" {
  if (analysis.targetRole === "human_review" || analysis.targetRole === "unknown") return "blocked";
  if (verification?.trustVerdict === "blocked") return "blocked";
  if (verification?.trustVerdict === "needs_review") return "needs_review";
  if (analysis.humanQuestions.length > 0 || analysis.confidence === "low" || analysis.sourceCoverage.filesTruncated.length > 0) {
    return "needs_review";
  }
  return "ready";
}

function frameworkTestHint(frameworkInfo: FrameworkInfo): string {
  const target = `${frameworkInfo.targetFramework} ${frameworkInfo.targetLanguage}`.toLowerCase();
  if (target.includes("aspnet") || frameworkInfo.targetLanguage === "csharp") {
    return "Use xUnit or NUnit with WebApplicationFactory/TestServer for API-level parity tests. Keep database access isolated with a test database or transactional fixture.";
  }
  if (frameworkInfo.targetLanguage === "python") {
    return "Use pytest with an HTTP test client such as FastAPI TestClient, Django test client, or Flask test client depending on the generated target.";
  }
  if (frameworkInfo.targetLanguage === "typescript" || frameworkInfo.targetLanguage === "javascript") {
    return "Use Jest/Vitest plus supertest for API-level parity tests.";
  }
  if (frameworkInfo.targetLanguage === "java") {
    return "Use JUnit with the target framework's integration-test harness, such as Spring MockMvc or QuarkusTest.";
  }
  return "Use the target framework's integration-test runner and prefer observable API behavior over implementation details.";
}

function buildComponentScaffold(
  analysis: ComponentAnalysis,
  frameworkInfo: FrameworkInfo,
  verification: ComponentVerification | undefined,
): string {
  const status = statusFor(analysis, verification);
  const scenarios = analysis.validationScenarios.length > 0
    ? analysis.validationScenarios
    : analysis.businessRules.map((rule) => `Prove parity for business rule: ${rule}`);
  const fallbackScenarios = scenarios.length > 0
    ? scenarios
    : [`Exercise ${analysis.component.name} through its public API and compare source and target observable behavior.`];

  const businessRules = analysis.businessRules.length > 0
    ? analysis.businessRules.map((rule) => `- ${rule}`).join("\n")
    : "- No concrete business rules were extracted. Review the component doc before writing tests.";
  const questions = analysis.humanQuestions.length > 0
    ? analysis.humanQuestions.map((q) => `- ${q}`).join("\n")
    : "- None.";
  const verificationSummary = verification
    ? `${verification.totals.verified}/${verification.totals.claimsChecked} claims verified; verdict=${verification.trustVerdict}`
    : "No verifier output was available.";

  return `# Parity Test Scaffold: ${analysis.component.name}

_Generated by CCS. This is a test planning artifact, not finished production test code._

## Gate

- **Implementation status:** ${status}
- **Verification:** ${verificationSummary}
- **Target:** ${frameworkInfo.targetFramework} (${frameworkInfo.targetLanguage})
- **Suggested test style:** ${frameworkTestHint(frameworkInfo)}

If the status is \`needs_review\` or \`blocked\`, resolve the questions below before asking a coding agent to turn this scaffold into executable tests.

## Business Rules Under Test

${businessRules}

## Human Questions To Resolve First

${questions}

## Scenario Checklist

${fallbackScenarios.map((scenario, index) => `${index + 1}. [ ] ${scenario}`).join("\n")}

## Suggested Test Skeleton

\`\`\`text
describe "${analysis.component.name} parity" {
${fallbackScenarios.map((scenario, index) => `  test "${index + 1}. ${scenario.replace(/"/g, "'")}" {
    arrange: create source-equivalent input and target test fixture
    act: call the migrated ${analysis.component.name} behavior through its public boundary
    assert: response/status/data/errors match the legacy behavior documented in components/${analysis.component.name}.md
  }`).join("\n\n")}
}
\`\`\`

## Source Files

${analysis.component.filePaths.map((path) => `- ${path}`).join("\n") || "- unknown"}
`;
}

export async function writeTestScaffolds(
  layout: RunLayout,
  analyses: ComponentAnalysis[],
  frameworkInfo: FrameworkInfo,
  verifications: Map<string, ComponentVerification>,
): Promise<TestScaffoldSummary> {
  await fs.mkdir(layout.testScaffoldsDir, { recursive: true });

  const files: TestScaffoldSummary["files"] = [];
  for (const analysis of analyses) {
    const verification = verifications.get(analysis.component.name);
    const path = join(layout.testScaffoldsDir, `${slugify(analysis.component.name)}.parity.md`);
    await fs.writeFile(path, buildComponentScaffold(analysis, frameworkInfo, verification), "utf-8");
    files.push({
      component: analysis.component.name,
      path,
      scenarioCount: Math.max(analysis.validationScenarios.length, analysis.businessRules.length, 1),
      status: statusFor(analysis, verification),
    });
  }

  const index = [
    "# Parity Test Scaffolds",
    "",
    "These files turn CCS validation scenarios into concrete testing work for Codex, Claude Code, or a QA engineer.",
    "They are intentionally scaffold-level artifacts: review the gate first, then ask the coding agent to convert ready items into executable tests in the target project.",
    "",
    "| Component | Status | Scenarios | File |",
    "|-----------|--------|-----------|------|",
    ...files.map((file) => `| ${file.component} | ${file.status} | ${file.scenarioCount} | \`${file.path.split(/[\\/]/).pop()}\` |`),
    "",
  ].join("\n");
  await fs.writeFile(join(layout.testScaffoldsDir, "README.md"), index, "utf-8");

  return { dir: layout.testScaffoldsDir, files };
}

